; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_f103rb]
platform = ststm32
board = genericSTM32F103RB
framework = arduino
build_flags = -DPNUM_NOT_DEFINED=0xFFFFFFFF
							-DSTM32F103xB
							-DPIN_WIRE_SDA=PB7 -DPIN_WIRE_SCL=PB6
							-DPIN_WIRE1_SDA=PB11 -DPIN_WIRE1_SCL=PB10
upload_protocol = stlink
board_build.mcu = stm32f103rbt6
