[platformio]
default_envs=STM32F105RBT6

[env:STM32F105RBT6]
platform = ststm32@17.6.0
board = genericSTM32F105RB
framework = arduino
build_flags = -DPNUM_NOT_DEFINED=0xFFFFFFFF
upload_protocol = stlink
board_build.variants_dir = variants
board_build.variant = Generic_F105Rx
